//------------------------------------------------------------------------
// Copyright(c) 2026 Yonie.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename	"WetCompressor.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"WetCompressor VST3 (64Bit)"
#else
#define stringFileDescription	"WetCompressor VST3"
#endif
#define stringCompanyName		"Yonie\0"
#define stringLegalCopyright	"Copyright(c) 2026 Yonie."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
